# Generated by Django 2.2.6 on 2022-07-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220725_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группу', 'verbose_name_plural': 'группы'},
        ),
    ]
