# Generated by Django 2.2.6 on 2022-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220725_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='У группы обязательно                                   должно быть описание', verbose_name='Краткое описание'),
        ),
    ]
