# Generated by Django 2.2.16 on 2022-08-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
    ]
